<?php 
include_once ( '../../init_session.php' );
$db = getDb();
$aa_inst_id=$session->instance['aa_inst_id'];	

/************************************************************
 * get saved days for app reset from db @ table app_config. *
 * (to check checkboxes if needed)                          *
 ************************************************************/
$config_keys = array();
$config_keys[ 0 ] = 'monday';
$config_keys[ 1 ] = 'tuesday';
$config_keys[ 2 ] = 'wednesday';
$config_keys[ 3 ] = 'thursday';
$config_keys[ 4 ] = 'friday';
$config_keys[ 5 ] = 'saturday';
$config_keys[ 6 ] = 'sunday';

// get all config vars according to this instance
$sql = "SELECT * FROM `app_config` WHERE `aa_inst_id` = '".$aa_inst_id."'";
try{
	$result = $db->fetchAll( $sql );
} catch(Exception $e) {
	// the deal should be in the db!
	echo "exception: no data found: ".$sql;
	exit(0);
}

// save all (un-)checked days / filter the days out of the config vars from the db
$checkedDays = array();
for( $index = 0; $index < count( $result ); $index++ ) {
	switch( $result[ $index ]['config_key'] ) {
		// monday
		case $config_keys[ 0 ]:
			if( $result[ $index ]['config_value'] == '1' ) {				 
				// add a checked attribute to the checkbox for monday
				$checkedDays['monday'] = 1;				
			} else {				
				$checkedDays['monday'] = 0;				
			}			
			break;
		// tuesday
		case $config_keys[ 1 ]:
			if( $result[ $index ]['config_value'] == '1' ) {
				// add a checked attribute to the checkbox for monday
				$checkedDays['tuesday'] = 1;
			} else {
				$checkedDays['tuesday'] = 0;
			}
			break;
		// wednesday
		case $config_keys[ 2 ]:
			if( $result[ $index ]['config_value'] == '1' ) {
				// add a checked attribute to the checkbox for monday
				$checkedDays['wednesday'] = 1;
			} else {
				$checkedDays['wednesday'] = 0;
			}
			break;
		// thursday
		case $config_keys[ 3 ]:
			if( $result[ $index ]['config_value'] == '1' ) {
				// add a checked attribute to the checkbox for monday
				$checkedDays['thursday'] = 1;
			} else {
				$checkedDays['thursday'] = 0;
			}
			break;
		// friday
		case $config_keys[ 4 ]:
			if( $result[ $index ]['config_value'] == '1' ) {
				// add a checked attribute to the checkbox for monday
				$checkedDays['friday'] = 1;
			} else {
				$checkedDays['friday'] = 0;
			}
			break;		
		// saturday
		case $config_keys[ 5 ]:
			if( $result[ $index ]['config_value'] == '1' ) {
				// add a checked attribute to the checkbox for monday
				$checkedDays['saturday'] = 1;
			} else {
				$checkedDays['saturday'] = 0;
			}
			break;
		// sunday
		case $config_keys[ 6 ]:
			if( $result[ $index ]['config_value'] == '1' ) {
				// add a checked attribute to the checkbox for monday
				$checkedDays['sunday'] = 1;
			} else {
				$checkedDays['sunday'] = 0;
			}
			break;
	}
}

if (!$session->fb['is_admin']){?>
	<div class="alert alert-block">
		<a class="close" data-dismiss="alert">x</a>
		<h4 class="alert-heading">Warning!</h4>
		<p><?=__p("Only admins can access this page");?></p>
	</div>
<?php } else {?>
	<div id="msg-container"></div>
	<div class="admin-getwinner">
		<div class="page-header">
			<h1><?=__p("Reset");?></h1>
		</div>
		
		<form class="form-horizontal">
			<fieldset>
				<legend><?php __p("Manual reset")?></legend>
				<div class="form-actions">
					<span class="btn btn-primary" onclick="resetLottery();"><i class="icon-repeat icon-white"></i> <?php __p("Reset lottery now")?></span>
				</div>
			</fieldset>
		</form>
		<?php if ($session->config['admin_reset_automatic']['value']) {?>
			<form class="form-horizontal">
				<fieldset>
					<legend><?php __p("Automatic reset")?></legend>
					<div class="control-group">
						<label class="control-label" for="optionsCheckboxList"><?=__p("Reset on these weekdays");?></label>
						<div class="controls">
						  <label class="checkbox">
							<input value="1" id="check_monday" Name="check_monday" type="checkbox" title="<?=__p("Monday");?>" <? if( $checkedDays['monday'] == 1 ) {?>checked<?}?>/>
							<?=__p("Monday");?>
						  </label>
						  <label class="checkbox">
							<input value="1" id="check_tuesday" Name="check_tuesday" type="checkbox" title="<?=__p("Tuesday");?>" <? if( $checkedDays['tuesday'] == 1 ) {?> checked <?}?>/>
							<?=__p("Tuesday");?>
						  </label>
						  <label class="checkbox">
							<input value="1" id="check_wednesday" Name="check_wednesday" type="checkbox" title="<?=__p("Wednesday");?>" <? if( $checkedDays['wednesday'] == 1 ) { ?> checked <?}?> />
							<?=__p("Wednesday");?>
						  </label>
						  <label class="checkbox">
							<input value="1" id="check_thursday" Name="check_thursday" type="checkbox" title="<?=__p("Thursday");?>" <? if( $checkedDays['thursday'] == 1 ) { ?> checked <?}?> />
							<?=__p("Thursday");?>
						  </label>
						  <label class="checkbox">
							<input value="1" id="check_friday" Name="check_friday" type="checkbox" title="<?=__p("Friday");?>" <? if( $checkedDays['friday'] == 1 ) { ?> checked <?}?> />
							<?=__p("Friday");?>
						  </label>
						  <label class="checkbox">
							<input value="1" id="check_saturday" Name="check_saturday" type="checkbox" title="<?=__p("Saturday");?>"<? if( $checkedDays['saturday'] == 1 ) {?> checked <?}?> />
							<?=__p("Saturday");?>
						  </label>
						  <label class="checkbox">
							<input value="1" id="check_sunday" Name="check_sunday" type="checkbox" title="<?=__p("Sunday");?>"<? if( $checkedDays['sunday'] == 1 ) {?> checked <?}?> />
							<?=__p("Sunday");?>
						  </label>
						  <p class="help-block"><strong><?=__p("Note");?>:</strong> <?=__p("The lottery will be reset at 00:01 o'clock on the selected days.");?></p>
						</div>
					</div>
					<div class="form-actions">
						<span class="btn btn-primary" onclick="setWeekdays();"><i class="icon-ok icon-white"></i> <?php __p("Save settings")?></span>
					</div>
				</fieldset>
			</form>
		<?php } ?>
	</div>

	<div class="modal hide fade" id="modal-reset">
	  <div class="modal-header">
		<a class="close" data-dismiss="modal">x</a>
		<h3><?=__p("Warning")?></h3>
	  </div>
	  <div class="modal-body">
		<p><?=__p("Do you really want to reset the lottery?");?></p>
	  </div>
	  <div class="modal-footer">
		<a href="#" data-dismiss="modal" class="btn btn-primary" onclick="reset();"><?=__p("Reset now");?></a>
		<a href="#" data-dismiss="modal" class="btn"><?=__p("No");?></a>
	  </div>
	</div>

	<script type="text/javascript">
	  function reset_data()
	  {
		if(jQuery("#del_participation").is(':checked') == true )
		  var del_p= 1;
		else
		  var del_p= 0;

		if(jQuery("#del_tracking").is(':checked') == true )
		  var del_t= 1;
		else
		  var del_t= 0;

		if(del_p == 0 && del_t == 0)
		{
			jQuery("#select-options").dialog({
				modal: true
			});
		  return false;
		}

		if(del_p == 1 && del_t == 1)
			jQuery("#delete-participants-tickets").dialog({
				modal: true
			});
		else if(del_p == 1 && del_t == 0)
			jQuery("#delete-participants").dialog({
				modal: true
			});
		else if(del_p == 0 && del_t == 1)
			jQuery("#delete-tickets").dialog({
				modal: true
			});
		jQuery("#reset_form").submit();
	  };

	  /****************************************************
	   * Save the checkbox values to app_config db-table. *
	   ****************************************************/
	function setWeekdays() {
		$("#mMessage").remove();
		$.ajax({	
			type : 'POST',
			async: true,
			url  : 'ajax/store_weekdays.php',
			data : ({			
				aa_inst_id:    '<?=$session->instance['aa_inst_id']?>',
				monday:    $('#check_monday:checked').val(),
				tuesday:   $('#check_tuesday:checked').val(),
				wednesday: $('#check_wednesday:checked').val(),
				thursday:  $('#check_thursday:checked').val(),
				friday:    $('#check_friday:checked').val(),
				saturday:  $('#check_saturday:checked').val(),
				sunday:    $('#check_sunday:checked').val()
				
			}),	
			/*****************************************************************
			 * this function gets executed when the ajax call above returns. *
			 *****************************************************************/
			success: function( data ){		
				if( data.indexOf( "true" ) >= 0 ) {				
					$('<div class="alert alert-success"><a class="close" data-dismiss="alert">x</a>'+
							'<?=__p("The settings for the automatic reset have been saved.");?>' +
						'</div>').prependTo("#msg-container");				
				} else {
					$('<div class="alert alert-block"><a class="close" data-dismiss="alert">x</a>'+
							'<?=__p("The settings can not be saved.");?>' +
						'</div>').prependTo("#msg-container");					
				}
			}
		});
	}

	  /*********************************************************
	   * Show popup to question if deletion shall be executed. *
	   *********************************************************/
	function resetLottery() {
		jQuery("#modal-reset").modal()
	}

	function reset(){
		// asynch ajax call
		$.ajax({
			type : 'POST',
			async: true,
			url  : 'ajax/resetRound.php',
			data : ({
				aa_inst_id: '<?=$session->instance['aa_inst_id']?>'
			}),
			/*****************************************************************
			 * this function gets executed when the ajax call above returns. *
			 *****************************************************************/
			success: function( data ){
				if( data.indexOf( "true" ) >= 0 ) {
					$('<div class="alert alert-success"><a class="close" data-dismiss="alert">x</a>'+
							'<?=__p("The lottery has been reset successfully.");?>' +
						'</div>').prependTo("#msg-container");
				} else {
					$('<div class="alert alert-block"><a class="close" data-dismiss="alert">x</a>'+
							'<?=__p("Lottery can not be reseted.");?>' +
						'</div>').prependTo("#msg-container");					
				}
			}
			
		});
		
	}
	function serializeObject(obj)
{
  if(isObject(obj) == false)
  {
    return('not object, can not display it'); 
    return false;
  }

  var str='';
  for(var key in obj)
  {
    str+=key + '=>' + obj[key] + '\n'; 
  }

  return(str);
}
function isObject(obj)
{
  if(typeof(obj) == 'undefined')
    return false;

  if(typeof(obj) != 'object')
    return false;

  if(obj == null)
    return false;

  if(obj == false)
    return false;

  return true;
}


	$(document).ready( function(){
		hide_loading();
	});
	</script>
<?php } ?>