<?php 
include_once ( '../init_session.php' );
?>
<div class="welcome-container">
	<div class="row">
		<ul class="thumbnails">
			<li class="span7">
			  <a href="#" class="thumbnail">
				<img src="<?=$session->config['image']['value'];?>" alt="<?=$session->config['title']['value'];?>">
			  </a>
			</li>
		</ul>
		<div class="span3">
		</div>
	</div>
	

</div> <!-- End welcome div live -->

<script>
$(document).ready( function(){
	hide_loading();
});
</script>
